import React,  {useEffect, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'


export default function Home() {
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  
  useEffect(() => {
     import("@line/liff").then((liff) => {
      liff
        .init({ liffId: process.env.NEXT_PUBLIC_LIFF_ID })
        .then(() => {
          setMessage('success')
        })
        .catch((err) => {
          console.warn({ err });
        });
    });
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
            
              <h1>Test</h1>
            
        </div>
      </main>
    </>
  )
}
