import React,  {useEffect, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'


export default function Home() {
  const [message, setMessage] = useState('テスト')
  const [error, setError] = useState('')
 
  useEffect(() => {
    import('@line/liff').then((liff) => {
      liff
        .init({
          liffId: process.env.NEXT_PUBLIC_LIFF_ID,
        })
        .then(() => {
          setMessage('LIFF 初期化成功');
        })
        .catch((err) => {
          setMessage('LIFF 初期化エラー');
          setError(err);
        });
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>{message}</h1>
      {error && <pre>{JSON.stringify(error, null, 2)}</pre>}
      </main>
    </>
  )
}
